name: Unzip files on push

on:
  push:
    paths:
      - "**.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and unzip files
        run: |
          for file in $(find . -name "*.zip"); do
            unzip -o "$file" -d .
            rm "$file"
          done

      - name: Commit extracted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Extracted files from ZIP"
          git push
